// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	RequestString
	Response
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestString struct {
	Mess string `protobuf:"bytes,1,opt,name=mess" json:"mess,omitempty"`
}

func (m *RequestString) Reset()                    { *m = RequestString{} }
func (m *RequestString) String() string            { return proto1.CompactTextString(m) }
func (*RequestString) ProtoMessage()               {}
func (*RequestString) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestString) GetMess() string {
	if m != nil {
		return m.Mess
	}
	return ""
}

type Response struct {
	Sent bool `protobuf:"varint,2,opt,name=sent" json:"sent,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetSent() bool {
	if m != nil {
		return m.Sent
	}
	return false
}

func init() {
	proto1.RegisterType((*RequestString)(nil), "proto.RequestString")
	proto1.RegisterType((*Response)(nil), "proto.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Ping service

type PingClient interface {
	SendString(ctx context.Context, in *RequestString, opts ...grpc.CallOption) (*Response, error)
}

type pingClient struct {
	cc *grpc.ClientConn
}

func NewPingClient(cc *grpc.ClientConn) PingClient {
	return &pingClient{cc}
}

func (c *pingClient) SendString(ctx context.Context, in *RequestString, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.Ping/SendString", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ping service

type PingServer interface {
	SendString(context.Context, *RequestString) (*Response, error)
}

func RegisterPingServer(s *grpc.Server, srv PingServer) {
	s.RegisterService(&_Ping_serviceDesc, srv)
}

func _Ping_SendString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).SendString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Ping/SendString",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).SendString(ctx, req.(*RequestString))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ping_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Ping",
	HandlerType: (*PingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendString",
			Handler:    _Ping_SendString_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto1.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xca, 0x5c,
	0xbc, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0xc1, 0x25, 0x45, 0x99, 0x79, 0xe9, 0x42, 0x42,
	0x5c, 0x2c, 0xb9, 0xa9, 0xc5, 0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92,
	0x1c, 0x17, 0x47, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0x48, 0xbe, 0x38, 0x35, 0xaf,
	0x44, 0x82, 0x49, 0x81, 0x51, 0x83, 0x23, 0x08, 0xcc, 0x36, 0xb2, 0xe6, 0x62, 0x09, 0x00, 0xe9,
	0x35, 0xe6, 0xe2, 0x0a, 0x4e, 0xcd, 0x4b, 0x81, 0x9a, 0x24, 0x02, 0xb1, 0x49, 0x0f, 0xc5, 0x7c,
	0x29, 0x7e, 0xb8, 0x28, 0xc4, 0xc0, 0x24, 0x36, 0x30, 0xdf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x0f, 0x14, 0x38, 0x59, 0xa0, 0x00, 0x00, 0x00,
}
